In [2]:
import datapackage
import pandas

In [4]:
data_url = 'https://datahub.io/core/dac-and-crs-code-lists/datapackage.json'
package = datapackage.Package(data_url)

In [6]:
resources = package.resources

In [8]:
[resource.name for resource in resources]

['validation_report',
 'dac-members_csv',
 'multilateral-donors_csv',
 'non-dac-donors_csv',
 'private-donors_csv',
 'agencies_csv',
 'nature-of-submission_csv',
 'recipients_csv',
 'channel-codes_csv',
 'collaboration-types_csv',
 'flow-types_csv',
 'finance-types_csv',
 'finance-type-categories_csv',
 'aid-types_csv',
 'aid-type-categories_csv',
 'sectors_csv',
 'sector-categories_csv',
 'dac-members_json',
 'multilateral-donors_json',
 'non-dac-donors_json',
 'private-donors_json',
 'agencies_json',
 'nature-of-submission_json',
 'recipients_json',
 'channel-codes_json',
 'collaboration-types_json',
 'flow-types_json',
 'finance-types_json',
 'finance-type-categories_json',
 'aid-types_json',
 'aid-type-categories_json',
 'sectors_json',
 'sector-categories_json',
 'dac-and-crs-code-lists_zip',
 'dac-members',
 'multilateral-donors',
 'non-dac-donors',
 'private-donors',
 'agencies',
 'nature-of-submission',
 'recipients',
 'channel-codes',
 'collaboration-types',
 'flow-types',
 'finance-types',
 'finance-type-categories',
 'aid-types',
 'aid-type-categories',
 'sectors',
 'sector-categories']

In [15]:
resources[1].descriptor['path']

'https://pkgstore.datahub.io/core/dac-and-crs-code-lists/dac-members_csv/data/d7c4baedcf4c26492fa72e50c6c12119/dac-members_csv.csv'

In [17]:
dac_members_csv = resources[1].descriptor['path']

In [19]:
pandas.read_csv(dac_members_csv)

    code          name_en               name_fr
0      1          Austria              Autriche
1      2          Belgium              Belgique
2      3          Denmark              Danemark
3      4           France                France
4      5          Germany             Allemagne
5      6            Italy                Italie
6      7      Netherlands              Pays-Bas
7      8           Norway               Norvège
8      9         Portugal              Portugal
9     10           Sweden                 Suède
10    11      Switzerland                Suisse
11    12   United Kingdom           Royaume-Uni
12    18          Finland              Finlande
13    20          Iceland               Islande
14    21          Ireland               Irlande
15    22       Luxembourg            Luxembourg
16    40           Greece                 Grèce
17    50            Spain               Espagne
18    61         Slovenia              Slovénie
19    68   Czech Republic    République tchèque
20    69  Slovak Republic   République slovaque
21    75          Hungary               Hongrie
22    76           Poland               Pologne
23   301           Canada                Canada
24   302    United States            Etats-Unis
25   701            Japan                 Japon
26   742            Korea                 Corée
27   801        Australia             Australie
28   820      New Zealand      Nouvelle-Zélande
29   918  EU Institutions  Institutions de l'UE